:concurrency: 5 
:pidfile: tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log 
:queues:
  - default 
  - mailers
  - med_reminder
  - [myqueue, 2]
 
development:
  :concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20